cipher_suites:
  allow_list:
    [
      "ECDHE-RSA-AES128-GCM-SHA256",
      "ECDHE-RSA-AES128-CBC-SHA",
      "ECDHE-RSA-AES128-SHA256",
      "ECDHE-RSA-AES256-GCM-SHA384",
      "ECDHE-RSA-AES256-CBC-SHA",
      "ECDHE-RSA-AES256-SHA384",
    ]
  default:
    listeners:
      [
        "ECDHE-RSA-AES128-GCM-SHA256",
        "ECDHE-RSA-AES128-CBC-SHA",
        "ECDHE-RSA-AES128-SHA256",
        "ECDHE-RSA-AES256-GCM-SHA384",
        "ECDHE-RSA-AES256-CBC-SHA",
        "ECDHE-RSA-AES256-SHA384",
      ]
    pools:
      [
        "ECDHE-RSA-AES128-GCM-SHA256",
        "ECDHE-RSA-AES128-CBC-SHA",
        "ECDHE-RSA-AES128-SHA256",
        "ECDHE-RSA-AES256-GCM-SHA384",
        "ECDHE-RSA-AES256-CBC-SHA",
        "ECDHE-RSA-AES256-SHA384",
      ]
